// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Account struct {
	ID        int32
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int32
	AccountID int32
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int32
	FromAccountID int32
	ToAccountID   int32
	Amount        int64
	CreatedAt     time.Time
}
